# Generated by Django 6.0 on 2026-01-19 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('avg_mood', models.FloatField(verbose_name='Среднее настроение')),
                ('avg_fatigue', models.FloatField(verbose_name='Средняя усталость')),
                ('avg_productivity', models.FloatField(verbose_name='Средняя продуктивность')),
            ],
            options={
                'verbose_name': 'Метрика учебной активности',
                'verbose_name_plural': 'Метрики учебной активности',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('study_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='tracker.studyday', verbose_name='Учебный день')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
    ]
